# Generated by Django 5.0.3 on 2024-11-05 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_barangayevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='date_registered',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='household_id',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='occupation',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.resident')),
            ],
        ),
    ]
