# Generated by Django 5.0.3 on 2024-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_resident_address_remove_resident_civil_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
