# Generated by Django 5.0.3 on 2024-11-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_barangayevent_attendees_household_resident_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
