# Generated by Django 5.0.3 on 2024-11-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_incidentreport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
