# Generated by Django 5.0.3 on 2024-11-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_barangayevent_attendees_resident_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayevent',
            name='overseen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='app.official'),
        ),
    ]
