# Generated by Django 5.0.3 on 2025-01-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_official_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='household_members', to='app.resident'),
        ),
    ]
